// <auto-generated />
using CodeFirstPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstPractice.Migrations
{
    [DbContext(typeof(ShelfContext))]
    [Migration("20201030194610_AddsShelfSeedData")]
    partial class AddsShelfSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstPractice.Models.Shelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("shelf");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Dairy"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Vegetables"
                        },
                        new
                        {
                            ID = -3,
                            Name = "Candy"
                        },
                        new
                        {
                            ID = -4,
                            Name = "Medicine"
                        },
                        new
                        {
                            ID = -5,
                            Name = "Baked goods"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
